version: '3.5'

services:
  app:
    build: .
    ports:
      - 3333:3333
    container_name: contact-service
    volumes:
      - .:/src
    networks:
      - main_network

networks:
  main_network:
    name: swarley_network